# Generated by Django 4.1.3 on 2022-11-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
